#!/bin/bash

echo ---------  CLEANING BUILD DIR  -------------------
mkdir -p build
rm build/*

echo ---------  COMPILING NIM EXAMPLES  ---------------
cd examples
nim c -o:./../build/drain_all drain_all.nim
nim c -o:./../build/produce_and_consume produce_and_consume.nim
nim c -o:./../build/two_step_pipeline two_step_pipeline.nim
nim c -o:./../build/two_step_pipeline_concurrent \
      --threads:on \
      two_step_pipeline_concurrent.nim
nim c -o:./../build/two_step_pipeline_parallel \
      --threads:on \
      two_step_pipeline_parallel.nim
cd ..

echo ---------  RUNNING EXAMPLES  ---------------------

echo
echo Running example: Drain all \(output sent to /dev/null\)
./build/drain_all > /dev/null

echo
echo Running example: Produce and consume
time ./build/produce_and_consume

echo
echo Running example: Two step pipeline
time ./build/two_step_pipeline

echo
echo Running example: Two step pipeline concurrent
time ./build/two_step_pipeline_concurrent

echo
echo Running example: Two step pipeline parallel
time ./build/two_step_pipeline_parallel
