#!/bin/bash

echo
echo ---------  CLEANING BUILD DIR  -------------------
echo
mkdir -p build
rm build/*

echo
echo ---------  COMPILING NIM EXECUTABLES  ------------
echo
nim c -o:./build/beanstalkd beanstalkd.nim

cd examples
nim c -o:./../build/drain_all drain_all.nim
cd ..

echo
echo ---------  RUNNING TEST  -------------------------
echo
./build/beanstalkd
